### PR TITLE
vscode: refactor

### PR DESCRIPTION
**Pull request by danielphan2003**
## Reasoning

This is an effort to refactor VS Code extensions and create a common overlay that other packages can based on. More over, metadata and passthrough are now sources-dependent, meaning that anything you want to expose to the final package should be within the sources. No more hacky workarounds to make meta parsing with [nvfetcher] work (https://github.com/divnix/devos-ext-lib/blob/118c751d68b2cd7ccf6504d52288aaafaaf0b0b6/src/vscode/meta.nix), and no more second-guessing which one comes from Open-VSX or VSMarketplace.

## Extension naming

By default, all extensions are exported as `${pname}` (i.e how you package your extension sources via nvfetcher toml).

To export them as `${publisher}.${name}` (nixpkgs-style), you can use `pkgs.vscode-utils.pkgBuilder'` when overriding vscode-extensions-builder. Note that they are all in lowercase.

## Migrating from older commit

- Sources that are passed to vscode-extensions-builder (and/or other) must now passthrough a publisher and a name.

- Refer to https://github.com/danielphan2003/nixpkgs/blob/0fffaf27270d1d424b9e07fd8982a84eb2ef8dc0/pkgs/default.nix#L12-L35 on how to package vs code extension sources. Also check out how to auto-generate Open-VSX extensions there.

Pinging @GTrunSec for feedback and suggestions.

[nvfetcher]: https://github.com/berberman/nvfetcher

### CODE REVIEW

**Review by GTrunSec — APPROVED** [review]

**Comment by GTrunSec** [comment]
Thanks. The `makeExtLib` could be very lovely changing. Maybe I will do some small modify for the next few days. But most commits look good to me.

**Comment by danielphan2003** [comment]
I have been using this for over a week now. Any extension that I throw at it loads fine with vscode, though it would be nice to have some CI tests...

That said, let me go ahead and merge this.

**Comment by GTrunSec** [comment]
You should update the Readme as well. Thanks

**Comment by danielphan2003** [comment]
Sure, should the doc be published at devos-ext-lib.divnix.com @blaggacao? I will publish the doc later.

**Pull request merged**
